### ISSUE TITLE
Rationale 

### ISSUE THREAD

**Issue by lilbaj** [lilbaj/just-your-type#1]
@muxlowc

For this assignment, I chose to use the lyrics from _Someone You Loved_ by Lewis Capaldi. This is his most famous song, and not that I have ever been in the situation he was in during the song, I empathized with him and found the heartbreak in the song. I think it's a feeling a lot of people can relate to, and I thought it would be interesting to work with this topic.

I chose _Caveat_ as the background text because I didn't want it to be as impactful as what's isolated in the box. I used _Oswald_ for the lyrics in the box because I found they resembled a lot to the text used on his EP _Breach_, which the song was initially released on. I also found it to create a good contrast and impact, which is what I wanted. Those specific lyrics are the most heartbreaking, so I wanted to make it stand out.

I used the perfect fifth type scale because it made the text a large size. I originally designed this concept with a large type scale, and I wanted to stick to it because I liked the way it looked.

I chose my colours based on the colours used on the _Breach_ EP. I thought they were dark, sad colours that played well into the meaning of the lyrics.

I didn't really use a grid because I used position absolute. However. I did use them to appropriately size my text so they would take up the right amount of space. I did use modules for creating my position elements, which is more effective and efficient than typing it all out in my main CSS file. 

There were a few moments where I struggled to get my boxed text to center in the middle of the page, but I found that using media queries in my main CSS file was the only way to fix that. Markbot also wouldn't except the link from the new Google Fonts setup, so I had to go back and use the older version. 

Overall, I like how it turned out, and I'm very happy with the design. I'm proud I was able to problem-solve all my issues by myself, cause this was not easy to do after coming back from a week off.

**Comment by muxlowc** [comment]
@lilbaj you can go ahead and close this issue - your mark should be up on the progress page now.
